services:
  server:
    container_name: node-server
    build: ./server
    ports:
      - "5001:5001"
    env_file:
      - ./server/.env
    restart: unless-stopped

  client:
    container_name: react-client
    build: ./client
    ports:
      - "3000:3000"
    depends_on:
      - server
    restart: unless-stopped
